backend:
  name: git-gateway
  branch: master
media_folder: public/img
publish_mode: editorial_workflow
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
  - label: "Menu"
    name: "menu"
    folder: "content/menus"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Menu URL", name: "menu-url", widget: "string"}
      - {label: "Is menu inline ?", name: "menu-inline", widget: "boolean", default: true}
      - {label: "Is menu special ?", name: "menu-special", widget: "boolean", default: false, required: false}
  - label: "Settings"
    name: "settings"
    file: "content/settings"
    identifier_field: name
    fields:
      - {label: "Site title", name: "site-title", widget: "string"}
      - {label: "Logo Alternate title", name: "logo-alt-title", widget: "string"}
      - {label: "Logo Image", name: "logo-image", widget: "image"}

